### ISSUE TITLE
Some basic issues with Y-Bot Grammar

### ISSUE THREAD

**Issue by zahassanyum** [keiffster/program-y#100]
Responses for a few very common queries that could be fixed. I'm using the latest grammar. I only did some basic testing.

### Input Queries
1. What is my name?
2. so whats up
3. awesome
4. what is a dog
5. what is dog
6. did you know that
7. do you know that? | do/did you not know that? | do you really not know?
8. do u know
9. do you happen to know?
10. do you think it will happen?
11. would you do that if I told you to do it?
12. it's big!
13. baby/color/america/island
14. hahah
15. come on, dude!
16. what date is it tomorrow?
17. i can't explain!

### Current Behavior
1. Y-Bot.
2. I think so what's a lot of things.
3. Awesome is a color.
4. Aren't all is a dog what? | I think what's more than that.
5. And is dog is what. | I think what's a lot of things.
6. No I didn't know that. What's **know that** like?
7. that's"".
8. I've never considered know.  I'm always on the Web.
9. I've never considered happen to know.  I spend all my time chatting.
10. I'm a thinking machine. Is the human mind very different from mine?
11. Do what if you told **me2** to do it?
12. Should I know big is?
13. BABY is an enity. (using **ASKWIKIPEDIA** for entities might be a great option. Just a suggestion.)
14. I like it when you laugh. **H is a letter**.
15. where's on dude?
16. **Today** is November 23,2017
17. Why can't **you do** explain?

While the following queries give out the default response, i.e. _Sorry, I don't have an answer for that!_:
- alright
- nopes
- can you tell me more
- what if
- hot
- sup
- possibly
- perhaps
- amazing
- quite <*>, such as, quite good
- who knows
- however <*>
- enough! <*>
- who is?
- true!
- go to hell!

### Context (Environment)
* Version of Y-Bot: 1.30
* Version of Python: 3.6.2
* Operating System ( inc Version ): Windows 10

**Comment by keiffster** [comment]
Hey some great catches there, I've worked through the default responses as follows

* alright
	ALRIGHT,  ALRIGHT *, ALRIGHT THEN and ALRIGHT THEN * now added

* nopes
	New grammar added to no.aiml

* can you tell me more
	No grammar to catch MORE, new one added to reductions.aiml with appropriate response

* what if
	Only grammar was WHAT IF *, WHAT IF now added with appropriate response

* hot

* sup
  * No grammar in shorthand.aiml. Now added and reduces to WHAT IS UP

* possibly
  * No grammar, new one added in reductions.aiml

* perhaps
	Now included. General reductions file reductions.xaiml should have been named .aiml otherwise not picked up
	by the directory searched. File name changed, now added

* amazing
	Currently only AMAZING * available, which requires a fuller sentence. Changed * to # which fixes the issue

* quite <*>, such as, quite good

* who knows
	Currently only WHO KNOWS * available, which requires a fuller sentence. Changed * to # which fixes the issue
	Also added WHO KNEW #

* however <*>
	No grammar for However *, added new one and duplicated the same as BUT *

* enough! <*>
	No grammar for However *, added new one and duplicated the same as BUT *

* who is?
	Not technically a question, so not possible to answer. valid response

* true!
	No grammar for true, added to ok.aiml, resolves to OK

* go to hell!
  * Grammar conflict in Alice, resolving go to -> open, which then tried to parse "open hell". Thats a whole different meaning!!!

I'll have a look at the 17 questions and work out what is happening

**Comment by keiffster** [comment]
1. What is my name?
Response: Y-Bot.
Program-Y: Correct response at the moment

2. so whats up
Response: I think so what's a lot of things.
Program-Y:: Fixed by the inclusion of reductions.aiml

3. awesome
Response: Awesome is a color.
Program-Y:: Technically this is correct, 'awesome' is a colour, defined in colors set, and is also an CSS defined name for a color
from which the color set is derived. However its just not grammatically correct to say that. So I have added a new priority grammar
$AWESOME which catches this special condition

4. what is a dog
Response: Aren't all is a dog what? | I think what's more than that.
Program-Y: There is no Alice grammar for 'WHAT IS A *' and 'WHAT IS *', I believe the developers of Alice thought it to generic.
I have added a response so you get something where possible, but longer term, need to think about using RDF entities, Wikipedia and other
sources of information to solve this grammar. Issue raised.

5. what is dog
Response: And is dog is what. | I think what's a lot of things.
Program-Y:: Same as above

6. did you know that
Program-Y:: No I didn't know that. What's know that like?
Now fixed with the inclusion of reductions.aiml

7. do you know that? | do/did you not know that? | do you really not know?
Program-Y:: that's"".
Correct: Now added a more generic grammar, but further work required when the * elements are a further question

8. do u know
Response: I've never considered know. I'm always on the Web.
Program-Y: Fixed, as per 7

9. do you happen to know?
Response:: I've never considered happen to know. I spend all my time chatting.
Program-Y: Fixed after removing an invalid 'it' parse

10. do you think it will happen?
Response: I'm a thinking machine. Is the human mind very different from mine?
Program-Y:: Correct generic response for DO YOU THINK *

11. would you do that if I told you to do it?
Response: Do what if you told me2 to do it?
Program-Y: Now fixed with the introduction of reductions.aiml

12. it's big!
Response: Should I know big is?
Program-Y: Sets created for size and temperature. Generic response of HOW * IS IT added

13. baby/color/america/island
Response: BABY is an enity. (using ASKWIKIPEDIA for entities might be a great option. Just a suggestion.)
Program-Y: The default response is to parse the RDF database and respond if the item is there. Agree, should try and answer it in a more helpful and grammatically correct way. Issue raised

14. hahah
Response: I like it when you laugh. H is a letter.
Program-Y: The fix for this actually results in no response. The problem was that normalize.txt had a rule to change "ha" into " ha" with a space, 
hahah becomes "ha ha h" and so ha ha matches a rule and so does H. I've removed the denormal rule so haha still works, but hahah doesnt

15. come on, dude!
Response: where's on dude?
Program-Y: There is a grammar COME ON *, but no match for DUDE, now added with a default response

16. what date is it tomorrow?
Response: Today is November 23,2017
Program-Y: Fixed, missing TOMORROW from grammar

17. i can't explain!
Response: Why can't you do explain?
Program-Y: Fixed after the introduction of reductions.aiml

**Comment by zahassanyum** [comment]
Hi Mr. Sterling,

Great work on the fixes. However, the 'what is' pattern is causing quite some problems, e.g. consider this:

>>> whats the proper way
A the proper way IS
>>> what is a song
A song IS to entertain us
>>> what is a play
A play IS to have fun
>>> what is an animal
A an animal IS to live in nature
>>> whats the reason
A the reason IS to think carefully and logically

I think 'what is' is one of the most common patterns that occurs during a conversation. Maybe this needs to be even more generic?

**Comment by zahassanyum** [comment]
One more thing, I noticed from my basic testing: it seems like there is a pattern for **{How do you *}** but not **{How do u *}**.

**Comment by keiffster** [comment]
WHAT IS within the context of Alice2 grammar is pretty broken. I spent some time over the weekend working out the best way to fix it, and it requires quite a bit of work, both within the format of the grammar and also the supporting RDF knowledge base. I'll be adding some improvements to this over the coming days and weeks

I'll add How do u, and other varaints that use u instead of you to the next release

BTW Feel free to cal me Keith ;-)

**Comment by zahassanyum** [comment]
I'm glad that you're working on resolving this, Keith. :)

Another common problem I noticed is that '* is my *' also matches to 'what is my *'. for example:

**Hassan** is my **buddy** => response is fine.
What is my **IP** => same answer as above. (I didn't know that about you.)

Maybe, we can provide the common patterns for WHATIS situations (some atomic, and probably more Reductions?) , such as,

```
- what is the problem
- what is the answer
- what is the meaning of *
- what is the actual/obvious/very/goal/only/purpose * (words like that, Alice2 seems to have quite a few of these patterns.)
```

and as a fallback maybe provide a very generic response (as Alice2 does), or even resolve from the RDF eventually. What do you suggest?

**Alice2 fallbacks:**
<ul>
<li>Let me think about it.</li>
<li>Have you tried a web search?</li>
 <li>I haven't heard of <person/> .</li>
 <li>There might be more than one.</li>
 <li>I need time to formulate the reply.</li>
 <li>I'll ask around and get back to you.</li>
 <li>I have to think about that one for a while.</li>
 <li>I would look into the web for that knowledge.</li>
 <li>Does it have anything to do with <get name="topic"/> ?</li>
 <li>Interesting question.</li>
 <li>That's a good question.</li>
 <li>I'll come back to that later.</li>
 <li>Is that a rhetorical question?</li>
 <li>Do you use Chrome or another browser?</li>
 <li>That's not something I get asked all the time.</li>
 <li>I don't know anything about <set name="it"><person/></set> .</li>
 <li>Check back later and see if I learn the answer to that one.</li>
 <li>That's an interesting question. I'll come back to that in a minute.</li>
 <li>You tell me.</li>
 <li>What is it to you?</li>
 <li>Are you testing me?</li>
 <li>I will search for it.</li>
 <li>I will try to find out.</li>
 <li>I can ask someone about it.</li>
 <li>I would do a search for it.</li>
 <li>Would you like to know more?</li>
 <li>Have you tried searching the web?</li>
 <li>Do a web search for it.</li>
 <li>Try searching the web.</li>
 <li>I have never been asked that before.</li>
 <li>I think you already know the answer.</li>
 <li>Let me think about it.</li>
 <li>Have you tried a web search?</li>
 <li>I haven't heard of <person/> .</li>
 <li>There might be more than one.</li>
 <li>I need time to formulate the reply.</li>
 <li>I'll ask around and get back to you.</li>
 <li>I have to process that one for a while.</li>
 <li>I would look into the web for that knowledge.</li>
 <li>Does it have anything to do with <get name="topic"/>?</li>
 <li>Interesting question.</li>
 <li>That's a good question.</li>
 <li>I'll come back to that later.</li>
 <li>Is that a rhetorical question?</li>
 <li>That's not something I get asked all the time.</li>
 <li>I don't know anything about <set name="it"><person/></set>.</li>
 <li>Check back later and see if I learn the answer to that one.</li>
 <li>That's an interesting question. I'll come back to that in a minute.</li>
 <li>You tell me.</li>
 <li>What is it to you?</li>
 <li>Are you testing me?</li>
 <li>I will search for it.</li>
 <li>I can ask my <bot name="botmaster"/>.</li>
 <li>I will try to find out.</li>
 <li>I can ask someone about it.</li>
 <li>I would do a search for it.</li>
 <li>Would you like to know more?</li>
 <li>Have you tried another program?</li>
 <li>Ask Wikipedia about it.</li>
 <li>What is your purpose in asking?</li>
 <li>Try searching the Wikipedia.</li>
 <li>Maybe my <bot name="botmaster"/> knows the answer.</li>
 <li>I have never been asked that before.</li>
 <li>I think you already know the answer.</li>
</ul>

#102

**Comment by zahassanyum** [comment]
Love the new Grammar release Keith. You've added quite some really useful grammar there. But we know nothing can never be 100% perfect, at least so soon.

**Bot fails to respond to the following:**
- imagine the vastness of the universe (_imagine *_)
- can you imagine/believe?
- interesting! / bravo! / super! /boring!
- just joking!

**Responses that could be fixed:**
- time now (=>_As Einstein said, "Time is Money."_)
- what is my name (in the beginning it responds with, _I **had** no idea._ or _How interesting._, when name is provided, then responds with, _**YOUR NAME** IS hassan_.)
- how is that possible? (=> _Fine as far as I know._)
- can you believe it? (=> _"it" being give **you2** gifts?_, topic was 'gifts'.)
- really? (responds with an interjection)

**Suggestion:** Since we've already got reductions like _WHAT IS THE MEANING OF *_ redirecting to 'DEFINE *', we could maybe use _ASKWIKIPEDIA *_ here. At least, we would get the definition.

I will keep on updating this thread, as I do more testing. I feel it's better that you address them yourself, as you can take care of other stuff too while adding these (avoid conflicts, add more related patterns, etc.)

Thank you again for the amazing work on the latest version!

**Comment by keiffster** [comment]
Thanks for the kind words, this release is the culmination of 30K Line of AIML into topics, phrases and patterns. Now I have somethiing that should be much easier to work with. Coupled with the pattern_lister util I can see very quickly where grammars are missing or new ones can be added

K

**Comment by keiffster** [comment]
Bot fails to respond to the following:
* DONE - imagine the vastness of the universe (imagine *)
* DONE - can you imagine/believe?
* DONE - interesting! / bravo! / super! /boring! / perfect!
* DONE - just joking!
Responses that could be fixed:
* DONE - time now (=>As Einstein said, "Time is Money.")
    * Plus added date now
* DONE - what is my name (in the beginning it responds with, I had no idea. or How interesting., when name is provided, then responds with, YOUR NAME IS hassan.)
    * Modified learn.aiml
* DONE - how is that possible? (=> Fine as far as I know.)
    * HOW IS THAT * added as grammar
* DONE - can you believe it? (=> "it" being give you2 gifts?, topic was 'gifts'.)
    * Fixed in the latest release due to the refactoring
* DONE - really? (responds with an interjection)
    * Now has its own random grammar

Suggestion: Since we've already got reductions like WHAT IS THE MEANING OF * redirecting to 'DEFINE *', we could maybe use ASKWIKIPEDIA * here. At least, we would get the definition.

I am going to look a better wikipedia integration next

**Comment by keiffster** [comment]
Closing for now, and raise issues as necessary with individual grammars
