### ISSUE TITLE
New Client ID

### ISSUE THREAD

**Issue by Vishal-7** [keiffster/program-y#108]
Hi,
      I am working on a bot and while hosting it on the web, i am not able to delete the temporary information of the previous session. What is the procedure to send a new client id, so that refreshing the page starts a new session?
Thanks in advance
PS: I am new to python coding

**Comment by keiffster** [comment]
Web chat client was originally created as an example of how to integrate with a web page but you are not the only one to ask how rouse it with multi clients so I’ve added the necessary change cookie code 

Give me another day or so and I’ll release 1.5 which contains the new and improved web client

K

**Comment by Vishal-7** [comment]
Thank you so much...!!

**Comment by ideasean** [comment]
Just a bump for multi-protocol client... eg extending BotClient so one can choose which clients to start instead of just one ... and then being able to switch between clients but maintain client id to ensure conversation continuity :-)

Skype For Business is great for being a trusted channel available across the org and devices, but then UCWA is limited and cannot support images/attachments. In this case we want to switch to over to a web client of some form that can then support rich media - and maybe the voice channel via WebRTC in future?

**Comment by keiffster** [comment]
Not an easy piece of work but it is on the backlog. Requires refactoring of all clients into a App -> Client model, and then writing a new app that loads multi clients. This also requires Bot to be extracted from Client and loaded in the App and then passed to all clients. So architecturally quite a destructive piece of work

Focus right now is to complete the update of a further 45K of categories to give Y-Bot a pretty comprehensive personality. Once that is up and out in the next week or so I’ll be turning back to more structural changes, multi client being one of them

Have a full backlog for my xmas vacation !!

K

**Comment by keiffster** [comment]
I've uploaded the code for the new webchat client, I've not finished testing so not increased the version number or created an official release, but I think it should do everything you need

**Comment by ideasean** [comment]
All good! What more for xmas vacation can you ask for? :-)
