### ISSUE TITLE
custom service

### ISSUE THREAD

**Issue by 00archer0** [keiffster/program-y#218]
i am trying to create a new rest service in template-y 
so please help me how to do it.
when i am doing this 

 it_help:
            classname: services.ITHELP.ITHELPservice
            method: GET
            host: localhost
            port: 4444
            url: /service/it_help

it giving me no module services
i have defined a service in src\templatey\

**Comment by keiffster** [comment]
Is you code for the service visible in PYTHONPATH

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by 00archer0** [comment]
can you explain this PYTHONPATH
i am not able get it.

**Comment by 00archer0** [comment]
![Capture](https://user-images.githubusercontent.com/29001634/58085042-9c2faa80-7bd9-11e9-9875-b78bcdb1cd5f.PNG)

check it out this is a screenshot this may be helpful for you.

**Comment by keiffster** [comment]
Can you provide details of the log file output


Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by 00archer0** [comment]
[template.log](https://github.com/keiffster/program-y/files/3201946/template.log)
sure , please find the attach file as log file.

**Comment by keiffster** [comment]
Thanks, can I ask you to delete the log file and then start your bot and then only try to ask you service question

The log file will then be only the data I need

Regards 

Keith
keith@keithsterling.com
07771 597630

**Comment by 00archer0** [comment]
[template.log](https://github.com/keiffster/program-y/files/3202046/template.log)
please find the log file. these are the after deletion 
![Capture](https://user-images.githubusercontent.com/29001634/58089442-60e5a980-7be2-11e9-801f-e355e2e5bc8c.PNG)
code breaks like this

**Comment by keiffster** [comment]
Ok, just so I understand, you have installed program-y via pip, then used the admin tool to download template bot, and have added a new Python file ITHELPservice.py into the folder src\services\ITHELP.

The only thing missing is that you need to add the src folder to PYTHONPATH so that programy can find your service

On Windows for example if template-y was installed in C:\Users\blaze\Documents\template-y

set PYTHONPATH=%PYTHONPATH;c:\Users\blaze\Documents\template-y\src

You can do this in the cmd shell you are running template-y in or follow the instructions at
https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages

**Comment by keiffster** [comment]
Did you get this solved ?
