### ISSUE TITLE
How to match optional set of words?

### ISSUE THREAD

**Issue by dilyararimovna** [keiffster/program-y#231]
Hello!

I would like to learn how to match patterns like the following example (non-working example, of course):
```
<pattern><regex pattern="(ALICE|BOB)" /> <regex pattern="(PLEASE|COULD YOU|COULD YOU PLEASE)?" /> DO * </pattern>
```
to match such patterns like "Alice, please, do it", "Alice, could you, please, do it", "Bob, do it".
The last example is the most important as I succeeded to use regex to match one of the given words (Alice or Bob) but I do not understand how to optionally (!) match one of the given words.

Thank you in advance!

**Comment by keiffster** [comment]
AIML matches at the word rather than the phrase level, so it will only match one word at a time.
Some of your phrases are multiple words which breaks AIML and theuse of the regex matcher.

It will match ALICE or BOB in the first pattern, but will not match 'COULD YOU' or 'COULD YOU PLEASE'

But this is the wrong way to go about AIML pattern matching, you should use multiple patterns if you want specifics or use of sets and * pattern matching.

For example you could create

```xml
<pattern>BOB * DO *</pattern>
<pattern>ALICE * DO *</pattern>
```

Or you can use a set of names

```xml
<pattern><set name="people" /> * DO *</pattern>
```

Where the set people.txt contains the names you want to match such as

```ini
BOB
ALICE
```

The former would be better if you only ever match BOB or ALICE, the latter if you want more names
