### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by impulsecorp** [keiffster/program-y#239]
You have a broken link at https://github.com/keiffster/program-y/wiki/Client-WebChat
At the bottom it links to "Web Chat Configuration" [ https://github.com/keiffster/program-y/wiki/Config-Client-WebChat ] but that link does not exist.

**Comment by SuperKogito** [comment]
I think broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.
