### ISSUE TITLE
Possible issue with <random>

### ISSUE THREAD

**Issue by Thielak** [keiffster/program-y#26]
Take this sample category
```	
<category>
	<pattern>TESTRANDOM</pattern>
	<template>
		<random>
			<li>Answer 1</li>
			<li>Answer 2</li>
			<li>Answer 3</li>
		</random>
	</template>
</category>
```

@JustArchi made a quick test, and out of 698 tries these were the results:
```
175     answer: "Answer 1"
177     answer: "Answer 2"
346     answer: "Answer 3"
```
As you can easily notice while the first 2 answers are very close, the third occurred almost twice as often as the others.

**Comment by JustArchi** [comment]
I think it might be connected with wrong range for some internal python randomizer, such as 0-3 range when it should be 0-2 only, and that wrong value overlapping last answer index, since it's always the last answer that is doubled.

This is only a wild guess though, maybe everything is OK, just RNG is pretty bad - that could be improved as well though if that's the case, since the difference is too big to claim it pseudo-random.

**Comment by Thielak** [comment]
I ran the same test with different amounts of possible answers \<random\> and got the same results, with the last one being twice as likely as the others.

2 options out of 1000 tries:
```
317     answer: "Answer 1"
683     answer: "Answer 2"
```
5 options out of 2000 tries:
```
340     answer: "Answer 1"
324     answer: "Answer 2"
302     answer: "Answer 3"
356     answer: "Answer 4"
678     answer: "Answer 5"
```
