### ISSUE TITLE
Can't use ampersand inside <template>

### ISSUE THREAD

**Issue by newdev7** [keiffster/program-y#32]
Hi,

I tried adding ampersand(&) symbol inside the template for one category. When I ran the code, it didn't return any error/warning. But none of the category is working after that. For every message it returned the default 'Sorry' message only. If I remove that ampersand and run the code, it works normally.

Why can't we add ampersand inside the `<template>`?

Thanks.

**Comment by Thielak** [comment]
In .xml files the characters `' " & < >` are reserved, to use them you have to escape them.
In your particular case you should use the sequence of characters `&amp;` whenever you want an ampersand to be displayed.

For example this category would work as you expected:
```
<category>
	<pattern>WHAT IS MY FAVOURITE SWEET SNACK</pattern>
	<template>M&amp;M's</template>
</category>
```
>\> what is my favourite sweet snack
> M&M's 

The reason why none of the categories in that file were working is because @keiffster added in https://github.com/keiffster/program-y/issues/23 a system that rejects a file if it's malformed instead of having the entire program crash outright.

**Comment by newdev7** [comment]
@Thielak Thanks for your information. Instead of escape the characters, I used codes to replace that. Now it is working as expected. Thank you.
