### ISSUE TITLE
Use_API_Keys missing from webchat config

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#33]
This key appears missing from the config/client/webchat.py config:

**webchat_client.configuration.webchat_configuration.use_api_keys**

This causes the webchat client to break when submitting a message - chatsrv throws an exception when trying to check it (line 42 in chatsrv.py).

Or I might be missing something :-)

**Comment by keiffster** [comment]
Config setting is missing from the command file for the webchat client, code currently didn't check for presence, code now checks for presence, just uploaded a new version of MASTER this morning

Also add a curl script to show how to call the client from the command line for testing

**Comment by ideasean** [comment]
It seems --debug is no longer supported when calling config.py?

**Comment by keiffster** [comment]
—debug never did anything, its a carry over from early days before I introduced full login support

The only time a debug option is used is on there web chat and rest clients which is passed through to the Flask App, but this setting is moved to the specific client configuration

Unfortunately in a rush to get the fix for web chat I pulled in a change to remove —debug across the system. Is it causing you any problems ?

K

**Comment by ideasean** [comment]
no real issue - I removed it from my .bat to launch. however, all your bot launcher .sh files also include it, so they may need updating.

**Comment by keiffster** [comment]
Yeap, they have all been updated now

Its time I started  moving to feature releases, until now I've done all the dev on master and just pushed when I felt like it. With more and more people using it, I need to keep master clear for quick defect fixes and use branch and pull request instead

**Comment by ideasean** [comment]
well, having more people using it is a 'good' problem to have! :-)
