### ISSUE TITLE
Twitter client setup instructions wiki - include permissions change?

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#38]
I've connected to Twitter API previously and knew how to create an application in Twitter to obtain the consumer and access tokens.

However on running I got this error in the log file:
`tweepy.error.TweepError: [{'code': 93, 'message': 'This application is not allowed to access or delete your direct messages.'}]`

It seems I didn't set the Twitter app permissions setting to:

> What type of access does your application need?
> Read only
> Read and Write << default
> **Read, Write and Access direct messages** << needed!

When the client connected, it retried for 15+ attempts and then blew the rate limit
`root       ERROR   Rate limit exceeded, sleeping for 15 minutes`

Once you change the permissions, it seems you also need to generate your tokens.

Might be good to include this in the wiki page :-)

**Comment by ideasean** [comment]
Got it working...  I now realise what impact the Twitter rate limit has, and why you set polling interval to 49 seconds. 15 requests per 15 mins! It doesn't really allow for a 'conversational' experience. Not a ProgramY issue - common to any bot using Twitter REST APIs. 

Seems a replacement API is coming but you have to request access to the BETA, and will require externally accessible host with TLS: [Account Activity API](https://dev.twitter.com/webhooks/account-activity)

Does the Facebook API have the same issue re 30 second polling?

**Comment by keiffster** [comment]
As you have found out the Twitter client does limit what you can do, but you'd be surprised what you can get away with. Each request is for all transactions, so a single call to get DMs or Follows brings all since the last call. You can reduce the polling interval to 30 and it still works, however during development its better to have a longer one as not to run into rate limits. I have run productions systems this way in the past with no issue from customers

The code I have does start to implement the streaming API, but is not finished. As you say it needs TLS and pass through your firewall, given the rate of development its a lot of effort at the moment, and very difficult on a train each morning and evening;-) so its on the backlog, just not got round to finishing it

**Comment by ideasean** [comment]
Understood ...  I can use Twitter for demo and am still keen to see Skype for business sometime soonish. I suspect it will be similar (as in server push vs polling) so hopefully there is some leverage.

I understand that it may need to wait until post 1.0 as its still just another client though. We need your brains on the bot brain :-)

**Comment by keiffster** [comment]
Added comments to the documentation, as no issue closing for now
