### ISSUE TITLE
Empty string input does not seem to be captured by <pattern>#</pattern>

### ISSUE THREAD

**Issue by keithsterling-FD** [keiffster/program-y#41]
Empty string input does not seem to be captured by <pattern>#</pattern>

Reported by Denis Kamotsky

**Comment by keiffster** [comment]
Same as issue 44 https://github.com/keiffster/program-y/issues/44

Both are reproducible, and therefore fix will be at the same time

**Comment by keiffster** [comment]
This is now fixed in master but slightly differently than you would expect

The parser used is XML, and so spaces are treat as non entities, therefore there is no way that the parser will ever get to a point where it sees " " or "".

Instead I've added a special config setting

bot:
    empty_string_srai: YEMPTY

Which the parser calls as a question when it is sent an empty or null string. You then implement a Priority grammar which can then be used

<aiml>

	<category>
		<pattern>#</pattern>
		<template>
		    <srai>YEMPTY</srai>
		</template>
	</category>

	<category>
		<pattern>$YEMPTY</pattern>
		<template>
		    UDC Hash Response
		</template>
	</category>
</aiml>

**Comment by keiffster** [comment]
Released on master
