### ISSUE TITLE
Question - sessionId

### ISSUE THREAD

**Issue by linediconsine** [keiffster/program-y#5]
HI, 
I am pretty new about collaborate in github and I now sure how start this discussion.

I was wondering if is possible to use program-y through a  REST shell.

the first step that is needed in my understanding is pass the request and session ID for every interaction for keep topic/etc for each used.

So, I suggest to allow used to specify user ID ( in no loop scenarios) on bash as first step

What do you think about this?

Marco

**Comment by keiffster** [comment]
Certainly is. The clientid attribute that is passed about everywhere is used to maintain state so that would allow rest and xmpp ( facebook & google ) clients to work correctly

The previous aims 1.0 engine I built had all these clients and I am currently recreating them in program-y at the moment

K

**Comment by keiffster** [comment]
Take a look at version 0.2.2 just released this morning, it includes a new client programy/clients/rest.py which is a REST server implemented in Flask for which you can pass a unique id in the url. This can be use id, session id, or something else that you client uses to uniquely id the customer
