### ISSUE TITLE
Feature request: Loading Speed

### ISSUE THREAD

**Issue by maxjread** [keiffster/program-y#52]
pyAIML has a feature where it saves a "bot.brain" file after loading in all the AIML. With a lot of AIML, this speeds up loading by approximately a factor of 10 on my Raspberry Pi. Would it be possible to implement that feature in program-y?
Great work on this, BTW!

**Comment by keiffster** [comment]
Hey, its actually something I'm working on, on a branch. It seems that I am able to pickle the entire aiml parse tree and then reload it in a fraction of the time. Just running some tests now and should be uploading in a day or so. 

Also with this branch, I've added some further speed improvements which reduce individual aiml file loading by a factor of 3-5 so that will help speed up the binary brain too

**Comment by keiffster** [comment]
Ok, I've pushed a new release to Master which contains the code for saving and reloading a brain to a binary file, I'm seeing about a 4x times speed increase in loading times after the initial save. 

Documentation to follow on the wiki, but to get a head start the 3 configuration items that control it are

brain:
    save_binary: false                                  <---- Save a binary file to the filename below
    load_binary: false                                   <---- Load a binary file, previously saved
    binary_filename: /tmp/y-bot.brain        <---- Name of the binary file

So you first set save to true load to false, run your bot and you will have a binary version of the brain
Then set save to false and load to true and every subsequent run will load the binary version of the file

**Comment by maxjread** [comment]
Brilliant, thanks.
