### ISSUE TITLE
webchat error 

### ISSUE THREAD

**Issue by narnikgamarnikus** [keiffster/program-y#54]
I get this error:

```
Traceback (most recent call last):
  File "../../src/programy/clients/webchat/chatsrv.py", line 5, in <module>
    from programy.config.client.webchat import WebChatClientConfiguration

```

And the reason is obvious: there is no this file.

What should the include WebChatClientConfiguration ?

**Comment by keiffster** [comment]
Apologies, didn't update all the webchat code when I refactored all of the config code base. Fixed and checked in master and just pushed the code 

K

**Comment by narnikgamarnikus** [comment]
@keiffster , I made a pull, and rewrote the REST client to another framework, asynchronous, but as simple as a flask.
It gives almost 10 times better performance.

I can try to do the same with web chat.

By the way, I have a good web chat on the websockets, also an asynchronous framework.
Material design and Vue.js

If you want, I will replace the code of the current web chat with my web chat, it is closer to production.

**Comment by keiffster** [comment]
Choice of web framework is always such a subjective choice, but its great that you have moved the web and REST clients forward.

How about we provide them as alternatives so that people have a choice.

As I am not familiar with those frameworks, I also need to be in a position to support them during ongoing development, so running them in parallel for a period of time will allow me to also become comfortable with them

If you want to create a number of pull requests with the various new elements, I’ll more than happy review and commit and then would love to have you come onboard as a formal contributor

K

**Comment by narnikgamarnikus** [comment]
@keiffster Perhaps you need to give users the choice that there is a web synchronous, and web-based asynchronous on web sockets, the client is synchronous and asynchronous.

This can make sense. For example, when it comes to high loads.

In any case, having more choice, users will have more opportunities.

I also wanted to note that you do not have anything to deploy. You do not talk about production anywhere in the documentation.

It would be possible, with each customer in a box, to put a bash script that would create a systemd unit, or something like that.

**Comment by keiffster** [comment]
The system is still very much under development, and as such I have not yet get round to adding the code for running the system as a daemon.

This is on the backlog of items to add. If you already have scripts that do this, would you consider submitting them to the code base

K

**Comment by narnikgamarnikus** [comment]
Maybe it makes sense to compose a todo so that the maintainers know, what do we have to do ?

I with pleasure, with your permission, would join, to the best of my ability.

**Comment by keiffster** [comment]
I already have a todo list in the Project Kanban Board

https://github.com/keiffster/program-y/projects/1



K
