### ISSUE TITLE
Linux & AWS

### ISSUE THREAD

**Issue by afharvey** [keiffster/program-y#76]
Hello @keiffster, looking at the kanban board I see some things I could assist with:

### Support for Linux ... Use VM instance and deploy to regularly from GitHub Platform ...
Travis or CircleCI (has a free tier) could run all the unit tests followed by a regression in a Linux environment. Both services can be triggered by Github commits.

###  Python as a Linux Daemon
Maybe as easy as making systemd service file or initd scripts depending on which distros you want to support.

### Deploy to AWS Server
EC2 shouldn't be too hard but I'm working on a project where I'd like to use part of program-y on AWS Lambda and later GCP functions.

Finally Docker. Are there any plans for an official image? This is something I'm doing anyway so I'm happy to help.

**Comment by keiffster** [comment]
Love to have you on board and contributing. CI is definitely a weak point in the platform at the moment and I'd love to have true continuous integration and deployment. Ultimately with a live Y-Bot ( or derivative ) that is running on AWS with the latest and greatest grammars for people to see it working in realtime.

Python as a Linux Demon is there in principle, I have a initd script on the Lightsail instance. Its not pretty and happy for some one to take that over and produce a more robust solution. Then AWS should be just the same as LightSail given its the same thing really. I think its more about having a production quality set of scripts AND documentation on the wiki

Docker, I use already on my Mac to give me instances on Rest services when I need them. I started looking at a Docker script but it's not gone very far due to other commitments

So in terms of contribution

* Continuous Integration
  * Run all unit and integration tests on each github check in
  * Run all code analysis on github check in
  * Alert development team on failures
* Continuous Deployment
  * Deploy latest passed build to AWS/Lightsaill instance 
  * Notify development team new build deployed
* Docker
  * Formal docker script/instance based on latest build

K

**Comment by keiffster** [comment]
Added to backlog so closing as not an open issue

**Comment by ohoachuck** [comment]
Hello,
any moved on a docker adaptation of Program-y ?
@afharvey have you done something on that ?
I'm trying to have a look, but I'm a newbie on Docker. So my dev try would probably be very poor :(
I'll be happy to share if I find how docker work and succeed on doing something.
O.

**Comment by keiffster** [comment]
Re-opening to allow us to collaborate on getting a docket instance working

**Comment by ohoachuck** [comment]
Hello,
as mentioned I have given a try on building a docker container for program-y. I'm just starting with docker and there are a lot of things that just work like magic (ie. I don't understand everything :) ).
Anyway, I don't really know how I can constructively contribute on this git repo, but here are my first explorations:

 - I have successfully created a container with Centos linux distribution + Python 3.6 + Program-y. And have uploaded to [Docker Cloud](https://cloud.docker.com/app/ohoachuck/repository/list) what I believe should be testable by anybody in a minute (given that you have created a free Dockr Cloud account and have docker installed). 

 - to do so I did nothing complicated, and just wrote a simple Dockerfile that looks like the following:
`############################################################
# Dockerfile to build program-y Application Containers
# Based on centos and python 3.6
############################################################

# Set the base image to centos
FROM centos

# File Author / Maintainer
MAINTAINER Olivier HO-A-CHUCK

# Update the sources list
RUN yum update -y

# Install basic applications
RUN yum install -y tar git curl nano wget dialog net-tools yum-utils

# Install Python and Basic Python Tools
RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm
RUN yum install -y python36u python36u-pip python36u-devel

# link python3.6 to python3
RUN ln -s /usr/bin/python3.6 /usr/bin/python3

# create program-y user with password=program-y
RUN useradd -m -p program-y program-y

# get program-y repo source as "program-y" user (could be your own repo with you own bot implementation)
RUN su -c 'git clone https://github.com/keiffster/program-y.git /home/program-y/program-y' - program-y

# Get pip to download and install requirements:
RUN pip3.6 install -r /home/program-y/program-y/requirements.txt

# Expose ports for flask API
EXPOSE 5000

# Copy the launch script inside the container
# launch.sh is : su -c 'cd /home/program-y/program-y/bots/y-bot/ && /home/program-y/program-y/bots/y-bot/y-bot-flask-rest.sh' - program-y
ADD /launch.sh /home/program-y/program-y/bots/y-bot/launch.sh

# Set the default directory where CMD will execute
WORKDIR /home/program-y/program-y/bots/y-bot/

# Set the default command to execute    
# when creating a new container
# Launch y-bot-flask-rest.sh as user "program-y"
# In unix (Linux, Mac OS X, BSD etc) systems, ports less than 1024 can not be bound to by normal users,
# only the root user can bind to those ports. So script like y-bot-webchat.sh would not be usable by
# user program-y unless default port 80 is changes to 8080 for instance 
CMD /bin/bash ./launch.sh
`
- This first Docker exploration might motivate some more experimented folks to move on this ? At least I hope this could help go a bit forward. I will continue my explorations.

**Comment by keiffster** [comment]
I am going to create a new project called Docker-y and use that to hold various docker config files

Yours will be the first and cents specific. 

I will do one for Ubuntu which is the variant I use

We can then start adding client specific ones such as rest, we chat etc

Thanks for all the hard work so far

**Comment by ohoachuck** [comment]
Hello,
talking of "hard work", my work was not hard at all (it was even interesting to finally get to play a bit more with docker - so very useful).
It's a good opportunity for me to thank YOUR hard work as program-y is THE HARD WORK here. Really thank you for this cool project. I believe AIML is a real free opportunity to do great conversational interfaces (as this will become a standard for Human Machine Interfaces). Program-y using our heart prefered language Python, with it's extended markups and in particular it's extensions is a truly flexible solution. I'm not really a developer anymore, and more a Marketing guy, but for me this Open Source project is the most promising project I know. There is always an up and a down motivation stage in a project depending of the workload and user gratitude. Be sure that you have my great gratitude for the had work done so far!

Then here's come also my best wishes for this new year coming. I wish you the expected success of program-y and many awards and gratifications :).

Back to more operational thoughts, I think default y-bot webchat port interface could preferably be 8080 rather than 80 to avoid 1) first time test conflict with existing webserver already running on our poor mac users 80 port, but more for 2) having a default greater than 1024 port used for a non root privileged user on Linux (linked with docker constraints).

O.

**Comment by keiffster** [comment]
BTW in the latest push to master I changed the port back to 8080 for webchat. This was an issue created by me incorrectly by doing a live test support AWS deployment. Anyway now back to 8080

**Comment by ohoachuck** [comment]
Ok, cool !
O.
