### ISSUE TITLE
Multiple clients for same bot

### ISSUE THREAD

**Issue by ideasean** [keiffster/program-y#80]
What changes would be required to allow one bot instance to support multiple clients? Eg, console, UCWA and a REST client (and maybe in future an MQ or Talk client)? I could run one instance just with REST, but that would also require writing separate standalone clients to handle console and UCWA sessions and turn those requests into REST API calls (a waste since most of the code to run these is already in Program-Y). 

Since the command line start procedure is to call a client, it seems to be an implicit assumption that there would be one client only? :-)

Perhaps there needs to be a generic starter/handler that reads what clients to start from config.yaml, and starts each on a separate thread (assuming console is always there?)

Or, extend console?

That then raises another question re whether conversation management and predicate-setting routines then thread-safe at a client conversation level?  There are multiple conversation lookups during question processing. If two questions from the same client are being processed at the same time (updating conversation or predicate vars), is there some risk? :-)

**Comment by keiffster** [comment]
Interesting idea, assume the working assumption here is that its multi clients using a single brain, otherwise memory consumption could start to get quite large with multi brains in the same client.

Based on that, there is no technical reason why this would not work. Program-Y is inherently threaded safe as all predicates are managed via the client id. Global predicates can be made immutable with the `override_properties` setting in bot which defaults to False anyway and stops your grammars overriding base predicates such as version, bot master etc. 

So adding multiple protocols to the same app is as simple as sharing the bot ( and hence the brain ) between them

Again interesting you mention talk client as an example, I am actually looking at how to run console and talk in the same client, mainly for testing but could be useful as 2 parallel ways of interacting with the same bot

I'm actually in that whole area of code at the moment as it's the area with the lowest unit test coverage and needs improving in the move to 1.0.0. So I'll have a think and explore and get back to your with some recommendations on how to create a multi protocol client

**Comment by sprinteroz** [comment]
You could try this its a multi protocol chat bot project name is Aires, and is written in Python. 
Link here: https://github.com/aichaos/aires

Also there is this multi protocol bot
https://github.com/txanatan/xbotpp

Thought you might like to merge it or get some ideas.

**Comment by keiffster** [comment]
Interesting, took a look at xbotpp, only supports irc at the moment, but I could grab the code from there

Aires only support xmpp and aol  and ybot already supports xmpp.

K

**Comment by keiffster** [comment]
I've been examing the code prior to the 1.0.0 release and while its very possible, its not a feature I want to add and delay 1.0.0 release.

The refactoring requires the introduction of another layer in the object hierarchy, lets call it App

App would instantiate Bot, which then instantiates Brain and the AIML is then loaded
App would have specific config which defines which protocols ( or clients ) to load
App would load each one, and pass the Bot ( and Brain ) to the necessary clients.
Bot and Brain are already thread-safe as long as each client uses a different clientid, however, this may require an additional a parameter so that the Bot and Brain taken clientid and userid as 2 different parameters. This would add additional thread safety and also allow clients to be distinquishable in log and conversation files.

If all goes well this will be key feature of V1.1

K

**Comment by ideasean** [comment]
Fair enough. This is 2nd priority here too, whereas merging 1.0.0 is 1st :-)

**Comment by keiffster** [comment]
0.99.2 is it really no further structural changes unless a major major issue is found

Just Lots and lots of documentation nowl

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by keiffster** [comment]
Planned for 1.1 or 1.2
